import type { RevenueVelocityFormulaTooltip } from '@/lib/dashboard-types'

export const revenueVelocityTooltips: Record<string, RevenueVelocityFormulaTooltip> = {
  realizedWonAmountInPeriod: {
    key: 'realizedWonAmountInPeriod',
    label: 'Факт денег периода',
    formula: 'Сумма сделок, выигранных в периоде по истории стадий или дате закрытия',
    description: 'Показывает деньги, фактически выигранные в окне наблюдения, даже если сделки были созданы раньше.',
  },
  activePipelineAmount: {
    key: 'activePipelineAmount',
    label: 'Активная воронка',
    formula: 'Сумма opportunity активных сделок на конец периода',
    description: 'Показывает полный денежный объём активной базы, которая ещё не выиграна и не проиграна.',
  },
  expectedPipelineAmount: {
    key: 'expectedPipelineAmount',
    label: 'Ожидаемые деньги воронки',
    formula: 'Σ opportunity × вероятность выигрыша текущей стадии',
    description: 'Показывается только при достаточной исторической базе по стадиям.',
  },
  expectedPipelineDelta: {
    key: 'expectedPipelineDelta',
    label: 'Изменение ожидаемых денег',
    formula: 'Ожидаемые деньги воронки сейчас - ожидаемые деньги воронки прошлого периода',
    description: 'Показывает, стала ли активная база денежно богаче или беднее за период.',
  },
  liveRevenueVelocity: {
    key: 'liveRevenueVelocity',
    label: 'Денежная скорость',
    formula: 'Σ expected amount активной сделки / ожидаемые дни до выигрыша',
    description: 'Показывается только при достаточной исторической базе по стадиям.',
  },
  velocityDelta: {
    key: 'velocityDelta',
    label: 'Изменение скорости',
    formula: 'Денежная скорость сейчас - денежная скорость прошлого периода',
    description: 'Показывает, ускорилась или замедлилась денежная система.',
  },
  systemValueCreated: {
    key: 'systemValueCreated',
    label: 'Системный прирост',
    formula: 'Факт денег периода + ожидаемые деньги воронки сейчас - ожидаемые деньги воронки прошлого периода',
    description: 'Учитывает не только закрытые деньги, но и изменение ожидаемой стоимости активной воронки.',
  },
  systemValuePerActionPoint: {
    key: 'systemValuePerActionPoint',
    label: '₽ системного прироста / балл',
    formula: 'Системный прирост / Взвешенные баллы действий периода',
    description: 'Показывает, сколько денежного прироста системы пришлось на один балл действий.',
    emptyState: 'Если действий нет, метрика не считается.',
  },
  realizedMoneyPerActionPoint: {
    key: 'realizedMoneyPerActionPoint',
    label: 'Реализованные ₽ / балл',
    formula: 'Факт денег периода / Взвешенные баллы действий периода',
    description: 'Оперативная метрика факта периода, не точная причинно-следственная связь.',
  },
  historicalMoneyPerActionPoint: {
    key: 'historicalMoneyPerActionPoint',
    label: 'Исторический ₽ / балл',
    formula: 'Деньги won созревших сделок / Баллы действий по этим сделкам',
    description: 'Калибрует, сколько денег исторически приносил один балл действий.',
  },
  estimatedFutureMoneyFromPeriodActions: {
    key: 'estimatedFutureMoneyFromPeriodActions',
    label: 'Оценка будущих денег от действий',
    formula: 'Баллы действий периода × Исторический ₽ / балл',
    description: 'Оценивает будущий денежный вклад действий периода через историческую калибровку.',
  },
  averageCheck: {
    key: 'averageCheck',
    label: 'Средний чек',
    formula: 'Сумма выигранных сделок / Количество выигранных сделок',
    description: 'Показывает средний размер успешной сделки в выбранной когорте.',
    emptyState: 'Если выигранных сделок нет, средний чек не считается.',
  },
  winRate: {
    key: 'winRate',
    label: 'Конверсия',
    formula: 'Выигранные сделки / Созданные возможности',
    description: 'Показывает, какая доля сделок из выбранной когорты дошла до успешного результата.',
  },
  averageCycleDays: {
    key: 'averageCycleDays',
    label: 'Средний цикл',
    formula: 'Среднее dateClosed - dateCreate по выигранным сделкам',
    description: 'Показывает средний путь успешной сделки от создания до закрытия.',
    emptyState: 'Если выигранных сделок нет или нет даты закрытия, цикл не считается.',
  },
  revenueVelocityPerDay: {
    key: 'revenueVelocityPerDay',
    label: 'Денежная скорость',
    formula: 'Средний чек × Количество возможностей × Конверсия / Средний цикл сделки',
    description: 'Показывает денежную скорость: сколько денег в день эта группа генерирует через свою воронку.',
    emptyState: 'Если нет выигранных сделок или средний цикл равен 0, денежная скорость не считается.',
  },
  moneyPerMeeting: {
    key: 'moneyPerMeeting',
    label: '₽ / встречу',
    formula: 'Сумма выигранных сделок / Количество встреч',
    description: 'Показывает, сколько денег приходится на одну встречу по сделкам выбранной когорты.',
    emptyState: 'Если встреч нет, метрика не считается.',
  },
  moneyPerConnectedCallOverThirtySeconds: {
    key: 'moneyPerConnectedCallOverThirtySeconds',
    label: '₽ / звонок >30 сек',
    formula: 'Сумма выигранных сделок / Количество звонков >30 секунд',
    description: 'Показывает, сколько денег приходится на один содержательный звонок.',
    emptyState: 'Если успешных звонков больше 30 секунд нет, метрика не считается.',
  },
  moneyPerConversionEvent: {
    key: 'moneyPerConversionEvent',
    label: '₽ / конв. мероприятие',
    formula: 'Сумма выигранных сделок / Количество конверсионных мероприятий',
    description: 'Показывает, сколько денег приходится на одно мероприятие на этапах Активация и Демонстрация.',
    emptyState: 'Если мероприятий нет или они ещё не подключены, метрика не считается.',
  },
  weightedActionPoints: {
    key: 'weightedActionPoints',
    label: 'Взвешенные баллы',
    formula: 'Звонки >30 сек × 1 + Встречи × 3 + Конв. мероприятия × 5 + Закрытые задачи × 0.5',
    description: 'Переводит разные действия в условные баллы, потому что встреча или мероприятие глубже двигают сделку.',
  },
  moneyPerWeightedActionPoint: {
    key: 'moneyPerWeightedActionPoint',
    label: '₽ / балл действий',
    formula: 'Сумма выигранных сделок / Взвешенные баллы действий',
    description: 'Показывает, сколько денег приносит один условный балл полезных действий.',
    emptyState: 'Если действий нет, метрика не считается.',
  },
  weightedActionPointsPerWin: {
    key: 'weightedActionPointsPerWin',
    label: 'Балл действий / выигрыш',
    formula: 'Взвешенные баллы действий / Выигранные сделки',
    description: 'Показывает, сколько условных баллов действий в среднем требуется для одной выигранной сделки.',
  },
  actionEfficiencyIndex: {
    key: 'actionEfficiencyIndex',
    label: 'Индекс эффективности действий',
    formula: '₽ / балл действий строки / Средний ₽ / балл действий по команде × 100',
    description: '100 — средний уровень команды. Выше 100 — действия монетизируются лучше среднего.',
  },
}
